export { default as Presentation } from './presentation/Presentation'
export { default as Recipes } from './recipes/Recipes'
export { default as Blog } from './blog/Blog'
export { default as About } from './about/About'
export { default as Join } from './join/Join'